from django.db import models

# Create your models here.
class docAnalisisModel(models.Model):
    usuario = models.CharField(null=False, max_length=75, default="")
    nombre = models.CharField(null=False, max_length=75, default="")
    objetivo = models.CharField(null=False, max_length=500, default="")
    identificador = models.CharField(null=False, max_length=30, default="")
    ind_met = models.CharField(null=False, max_length=500, default="")
    des_actividades = models.CharField(null=False, max_length=750, default="")
    diagrama_flujo = models.ImageField(upload_to="diagramas_flujo", null=False)
    categoria = models.CharField(null=False, max_length=75, default="")
    salida = models.CharField(null=False, max_length=500, default="")
    frecuencia = models.CharField(null=False, max_length=100, default="")
    introE = models.CharField(null=False, max_length=500, default="")
    alcanceE = models.CharField(null=False, max_length=500, default="")
    objetivosE = models.CharField(null=False, max_length=500, default="")
    arq1 = models.ImageField(upload_to="arquitectura", null=True, blank=True)
    arq2 = models.ImageField(upload_to="arquitectura", null=True, blank=True)
    arq3 = models.ImageField(upload_to="arquitectura", null=True, blank=True)
    comp1 = models.ImageField(upload_to="componentes", null=True, blank=True)
    comp2 = models.ImageField(upload_to="componentes", null=True, blank=True)
    comp3 = models.ImageField(upload_to="componentes", null=True, blank=True)
    des_componentesE = models.CharField(null=False, max_length=500, default="")

class docPruebasUnitariasModel(models.Model):
    usuario = models.CharField(null=False, max_length=75, default="")
    nombre_proceso = models.CharField(null=False, max_length=75, default="")
    objetivo = models.CharField(null=False, max_length=500, default="")
    identificador = models.CharField(null=False, max_length=30, default="")
    ind_met = models.CharField(null=False, max_length=500, default="")
    des_actividades = models.CharField(null=False, max_length=750, default="")
    diagrama_flujo = models.ImageField(upload_to="diagramas_flujo", null=False)
    categoria = models.CharField(null=False, max_length=75, default="")
    salida = models.CharField(null=False, max_length=500, default="")
    frecuencia = models.CharField(null=False, max_length=100, default="")
    nombre_proyecto = models.CharField(null=False, max_length=75, default="")
    encargado = models.CharField(null=False, max_length=75, default="")
    fase = models.CharField(null=False, max_length=100, default="")
    lugar_fecha = models.CharField(null=False, max_length=200, default="")
    req = models.CharField(null=False, max_length=500, default="")
    repo = models.CharField(null=False, max_length=250, default="")
    selec = models.CharField(null=False, max_length=250, default="")
    cod1 = models.ImageField(upload_to="codigo", null=True, blank=True)
    cod2 = models.ImageField(upload_to="codigo", null=True, blank=True)
    cod3 = models.ImageField(upload_to="codigo", null=True, blank=True)
    lineas = models.CharField(null=False, max_length=50, default="")

class docRequisitosModel(models.Model):
    usuario = models.CharField(null=False, max_length=75, default="")
    nombre_proceso = models.CharField(null=False, max_length=75, default="")
    objetivo = models.CharField(null=False, max_length=500, default="")
    identificador = models.CharField(null=False, max_length=30, default="")
    ind_met = models.CharField(null=False, max_length=500, default="")
    des_actividades = models.CharField(null=False, max_length=750, default="")
    categoria = models.CharField(null=False, max_length=75, default="")
    salida = models.CharField(null=False, max_length=500, default="")
    frecuencia = models.CharField(null=False, max_length=100, default="")
    proposito = models.CharField(null=False, max_length=500, default="")
    alcance = models.CharField(null=False, max_length=500, default="")
    referencias = models.ImageField(upload_to="referencias", null=True, blank=True)
    funcionalidades = models.CharField(null=False, max_length=500, default="")
    clases = models.CharField(null=False, max_length=500, default="")
    entorno = models.CharField(null=False, max_length=100, default="")
    req_f = models.CharField(null=False, max_length=600, default="")
    req_nf = models.CharField(null=False, max_length=600, default="")